title: 我的摄影博客
description: 展示我的摄影作品和摄影心得
baseurl: "" # 如果你的网站不在根目录，填写子目录名
url: "" # 你的域名

# Jekyll配置
theme: minima
plugins:
  - jekyll-feed

# 网站信息
author:
  name: 你的名字
  email: 你的邮箱
  description: 摄影师/博主
  social:
    twitter: yourtwitter
    instagram: yourinstagram
    github: yourgithub

# 相册配置
collections:
  gallery:
    output: true
    permalink: /gallery/:path/

# 构建配置
markdown: kramdown
highlighter: rouge
